In [1]:
#L2
import pandas as pd
info={
    "name": ["rahul","anjali", "sumit"],
    "cgpa": [9.1, 8.5, 9.3],
}
df=pd.DataFrame(info)
print(df)

     name  cgpa
0   rahul   9.1
1  anjali   8.5
2   sumit   9.3

In [2]:
#L3
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))
print(s[2])
s1=pd.Series([10,20,30,40], index=['a','b','c','d'])
print(s1)
print(s1['c'])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
3
a    10
b    20
c    30
d    40
dtype: int64
30

In [18]:
#L4
import pandas as pd
s1=pd.Series([10,20,30,40])
s2=pd.Series([100,200,300,400])
print(s1+s2)
s1[0]=500
print(s1)
changed_s1=s1.drop(0)
print(s1)
print(changed_s1)

0    110
1    220
2    330
3    440
dtype: int64
0    500
1     20
2     30
3     40
dtype: int64
0    500
1     20
2     30
3     40
dtype: int64
1    20
2    30
3    40
dtype: int64

In [7]:
#L5
import pandas as pd
#dataframe
info={
    "name": ["rahul","anjali", "sumit"],
    "age": [21,22,20],
    "cgpa": [9.1, 8.5, 9.3],
}
df=pd.DataFrame(info)
print(df, type(df)) 
print(df.columns)

df1=pd.DataFrame([["rahul",21,9.1],
                 ["anjali",22,8.5],
                 ["sumit",20,9.3]],
                 columns=["name","age","cgpa"])
print(df1)

import numpy as np
np_arr=np.array([[1,2,3],
                 [4,5,6],
                 ])
df2=pd.DataFrame(np_arr, columns=['a','b','c'])
print(df2)

     name  age  cgpa
0   rahul   21   9.1
1  anjali   22   8.5
2   sumit   20   9.3 <class 'pandas.core.frame.DataFrame'>
Index(['name', 'age', 'cgpa'], dtype='object')
     name  age  cgpa
0   rahul   21   9.1
1  anjali   22   8.5
2   sumit   20   9.3
   a  b  c
0  1  2  3
1  4  5  6

In [11]:
#L6
import pandas as pd
#csv dataset
df=pd.read_csv('pokemon.csv')
print(df, type(df))

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns] <class 'pandas.core.frame.DataFrame'>

In [16]:
#L7
import pandas as pd
#Methods
df=pd.read_csv('pokemon.csv')
print(df.head(10)) # Display first 10 rows ( default is 5)
print(df.tail(7)) # Display last 7 rows ( default is 5)
print(df.sample(5)) # Display random 5 rows
print(df.info()) # Display info about dataframe
print(df.describe()) # Display statistical summary of numerical columns
print(df.shape) # Display shape of dataframe (rows, columns)
print(df[df['Height'] == df['Height'].min()]) # pokemon with minimum height
print(df.columns) # Display column names
print(df.nunique()) # Display number of unique values in each column

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0
5   6   Charizard   Fire  Flying     1.7    90.5          0
6   7    Squirtle  Water     NaN     0.5     9.0          0
7   8   Wartortle  Water     NaN     1.0    22.5          0
8   9   Blastoise  Water     NaN     1.6    85.5          0
9  10    Caterpie    Bug     NaN     0.3     2.9          0
      No       Name     Type1   Type2  Height  Weight  Legendary
143  144   Articuno       Ice  Flying     1.7    55.4          1
144  145     Zapdos  Electric  Flying     1.6    52.6          1
145  146    Moltres      Fire  Flying     2.0    60.0          1
146  147    Dratini    Dragon     NaN     1.8     3.3          0
147  148  Dragonair    Dragon     NaN     4.0    16.5          0
148  149  Dragonite    Dragon  Flying     2.2   210.0          0
149  150     Mewtwo   Psychic     NaN     2.0   122.0          1
      No      Name     Type1   Type2  Height  Weight  Legendary
143  144  Articuno       Ice  Flying     1.7    55.4          1
94    95      Onix      Rock  Ground     8.8   210.0          0
24    25   Pikachu  Electric     NaN     0.4     6.0          0
113  114   Tangela     Grass     NaN     1.0    35.0          0
86    87   Dewgong     Water     Ice     1.7   120.0          0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         150 non-null    int64
 1   Name       150 non-null    object
 2   Type1      150 non-null    object
 3   Type2      67 non-null     object
 4   Height     150 non-null    float64
 5   Weight     150 non-null    float64
 6   Legendary  150 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 8.3+ KB
None
               No      Height      Weight   Legendary
count  150.000000  150.000000  150.000000  150.000000
mean    75.500000    1.200000   46.231333    0.026667
std     43.445368    0.963634   59.547388    0.161647
min      1.000000    0.200000    0.100000    0.000000
25%     38.250000    0.700000    9.925000    0.000000
50%     75.500000    1.000000   30.000000    0.000000
75%    112.750000    1.500000   56.375000    0.000000
max    150.000000    8.800000  460.000000    1.000000
(150, 7)
    No     Name   Type1 Type2  Height  Weight  Legendary
49  50  Diglett  Ground   NaN     0.2     0.8          0
Index(['No', 'Name', 'Type1', 'Type2', 'Height', 'Weight', 'Legendary'], dtype='object')
No           150
Name         150
Type1         15
Type2         11
Height        26
Weight       108
Legendary      2
dtype: int64

In [29]:
#L8&L9
import pandas as pd
df=pd.read_csv('globalairquality.csv')
df.describe()

#selecting the data
print(df['city']) 
print(df[['city','aqi']])
#indexed selection:iloc and loc for label based selection
print(df.loc[2])
print(df.loc[0:2])
print(df.iloc[0:2])
print(df.iloc[0:3:1])
print(df.loc[1,"aqi"])
df.loc[0,["city","aqi"]]
#df.iloc[0,["city","aqi"]] ______ is wrong
# iloc is numerical dependent indexer
df.columns
# city is 2, and
df.iloc[0:3,2]
df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]
#cell
df.at[0,"city"]
df.iat[0,2]

cities=df["city"].copy() # copy not view if direct change kiya toh original data gaya # fukked
cities[0]='mumbai'# copy 
cities

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object
           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]
timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783

   wind_speed
0       3.725
1       8.969
2       9.650
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088

   wind_speed
0       3.725
1       8.969
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783

   wind_speed
0       3.725
1       8.969
2       9.650
90

0          mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [1]:
#L10
import pandas as pd
df=pd.read_csv('globalairquality.csv')
#filtering
df[df["aqi"]>100]
#and=& , or=| , not =~
df[(df["aqi"]>100) & (df["temperature"]>30)]
aqi_data=df[df["aqi"]>100] [["city","aqi","temperature"]]

In [5]:
#L11
df.query("aqi>100")
api_value =90
df.query("aqi>@api_value")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17994,2025-11-19 12:25:17.554219,CH,Zurich,47.377,8.542,42.982,54.692,37.756,7.528,55.321,0.929,94,35.439,77.027,0.682
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642

In [15]:
#L12
#cleaning
#handle missing data
import pandas as pd
df=pd.read_csv('raw_data.csv')
df.isnull()#the misssing value ---->boolean (T/f)
df.isnull().sum() # in wht column , how much null item r there?
df.dropna() # empty cell row drop
df.dropna(axis=1) # empty cell column drop
df.fillna(0)
df.fillna(100)
df["age"].fillna(0)


cleaned_data=df.copy()
age_mean=df["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data
df.ffill() #forward fill 
df.bfill() #backward fill
df[["country","gender"]].duplicated()
# df[specific format if any].function(specfic format of funtion)
df2=df.copy()

df.drop_duplicates()
df.drop_duplicates(inplace=True)

In [19]:
#L13
import pandas as pd
df=pd.read_csv('raw_data.csv')
df.dtypes
df2=df.copy()
df2=df2.fillna(0)
df2=df2["age"].astype("int64").copy()
# type casting in pandas

df2.dtypes

aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [25]:
#L14
import pandas as pd
date_str=pd.Series(["2026-12-31"])
type(date_str.dtypes)

date_str=pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [ ]:
#L15
import pandas as pd
df=pd.read_csv('raw_data.csv')
df["gender"].str.lower
df["gender"].str.upper
df["gender"].str.capitalize()#oiginal data display
df["name"].str.split(" ")
#aman@gmail.com
#shrimon@gmail.com
#-----> f["name"].str.split("@")
df["country"].str.contains("usa",case=False) # case is needed to remove case senstivity
#if u r typing keeping case sentivity in mind than u dont need case function

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object